In [17]:
import pandas as pd
import numpy as np
from geopy.distance import distance
import concurrent.futures

In [18]:
data = pd.read_csv('corrected_latitude_longitude_details.csv')

In [19]:
 def generate_left_right_points(row):
    orig_point = (row.latitude, row.longitude)
    bearing_left = 270  # 270 degrees for left
    bearing_right = 90  # 90 degrees for right

    point_left = distance(meters=25).destination(orig_point, bearing_left)
    point_right = distance(meters=25).destination(orig_point, bearing_right)

    return (row.latitude, row.longitude, point_left.latitude, point_left.longitude, point_right.latitude, point_right.longitude)

In [20]:
with concurrent.futures.ThreadPoolExecutor() as executor:
    results = list(executor.map(generate_left_right_points, data.itertuples(index=False)))

# Create a DataFrame for the new points
new_data = pd.DataFrame(results, columns=['orig_latitude', 'orig_longitude', 'left_latitude', 'left_longitude', 'right_latitude', 'right_longitude'])

In [24]:
 new_data = pd.DataFrame(results, columns=['orig_latitude', 'orig_longitude', 'left_latitude', 'left_longitude', 'right_latitude', 'right_longitude'])

new_data

,orig_latitude,orig_longitude,left_latitude,left_longitude,right_latitude,right_longitude
0,10.004526,76.375986,10.004526,76.375758,10.004526,76.376214
1,10.004385,76.375502,10.004385,76.375274,10.004385,76.375730
2,10.004391,76.375115,10.004391,76.374887,10.004391,76.375343
3,10.004453,76.374769,10.004453,76.374541,10.004453,76.374997
4,10.004532,76.374565,10.004532,76.374337,10.004532,76.374793
5,10.004687,76.374424,10.004687,76.374196,10.004687,76.374652
6,10.004908,76.374324,10.004908,76.374096,10.004908,76.374552
7,10.005123,76.374212,10.005122,76.373983,10.005122,76.374440
8,10.005122,76.374227,10.005122,76.373999,10.005122,76.374455
9,10.005205,76.374201,10.005205,76.373973,10.005205,76.374429
10,10.005397,76.374103,10.005397,76.373875,10.005397,76.374331
11,10.005515,76.374046,10.005515,76.373818,10.005515,76.374274
12,10.005633,76.373989,10.005633,76.373761,10.005633,76.374217
13,10.005847,76.373968,10.005847,76.373740,10.005847,76.374196
14,10.006072,76.374049,10.006072,76.373821,10.006072,76.374277
15,10.006249,76.374211,10.006249,76.373983,10.006249,76.374439
16,10.006272,76.373975,10.006272,76.373747,10.006272,76.374203
17,10.006416,76.374388,10.006416,76.374160,10.006416,76.374616
18,10.006598,76.374555,10.006598,76.374327,10.006598,76.374783
19,10.006783,76.374723,10.006783,76.374495,10.006783,76.374951
20,10.006994,76.374841,10.006994,76.374613,10.006994,76.375069
21,10.006495,76.374201,10.006495,76.373973,10.006495,76.374429
22,10.006550,76.374170,10.006550,76.373942,10.006550,76.374398
23,10.006716,76.374118,10.006715,76.373890,10.006715,76.374346
24,10.007123,76.374170,10.007123,76.373942,10.007123,76.374398
25,10.007644,76.374641,10.007644,76.374413,10.007644,76.374869
26,10.007317,76.374128,10.007317,76.373900,10.007317,76.374356
27,10.007240,76.373939,10.007240,76.373711,10.007240,76.374167
28,10.007109,76.373636,10.007109,76.373408,10.007109,76.373864
29,10.007064,76.373548,10.007064,76.373320,10.007064,76.373776
30,10.007079,76.373404,10.007079,76.373176,10.007079,76.373632
31,10.007094,76.373260,10.007094,76.373032,10.007094,76.373488
32,10.007201,76.373008,10.007201,76.372780,10.007201,76.373236
33,10.007112,76.372791,10.007112,76.372563,10.007112,76.373019
34,10.006775,76.372777,10.006775,76.372548,10.006775,76.373005
35,10.006695,76.373054,10.006695,76.372826,10.006695,76.373283
36,10.006753,76.373492,10.006753,76.373264,10.006753,76.373720
37,10.006858,76.373783,10.006858,76.373555,10.006858,76.374011
38,10.006894,76.373876,10.006894,76.373648,10.006894,76.374104

In [22]:
new_data.to_csv('left_right_latitude_longitude_details.csv', index=False)

In [23]:
from collections import deque

class MovingTotal:
    def __init__(self):
        self.numbers = deque(maxlen=3)
        self.totals = set()
    
    def append(self, numbers):
        for num in numbers:
            self.numbers.append(num)
            if len(self.numbers) == 3:
                self.totals.add(sum(self.numbers))
    
    def contains(self, total):
        return total in self.totals

if __name__ == "__main__":
    movingtotal = MovingTotal()
    movingtotal.append([1, 2, 3, 4])
    print(movingtotal.contains(6))  # True
    print(movingtotal.contains(9))  # True
    print(movingtotal.contains(12)) # True
    print(movingtotal.contains(7))  # False
    movingtotal.append([5])
    print(movingtotal.contains(6))  # True
    print(movingtotal.contains(9))  # True
    print(movingtotal.contains(12)) # True
    print(movingtotal.contains(7))  # False

True
True
False
False
True
True
True
False